--
-- PostgreSQL database dump
--

-- \restrict v3OO9YPjRzMqjjRJiquerHReaQzYhRoadvS0EsuNI8XrWNXeyTp53tqtaY0xY0r

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: catalog_component; Type: TABLE; Schema: public; Owner: tam
--

CREATE TABLE public.catalog_component (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    deleted_by uuid,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    capacity_unit character varying(255) NOT NULL,
    capacity_unit_description character varying(255) NOT NULL,
    component_key character varying(255) NOT NULL,
    feature_name character varying(255) NOT NULL,
    ha_minimum integer NOT NULL,
    is_active boolean NOT NULL,
    machine_spec character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    per_machine_capacity double precision NOT NULL,
    reference_url character varying(255)
);


ALTER TABLE public.catalog_component OWNER TO tam;

--
-- Name: catalog_component_id_seq; Type: SEQUENCE; Schema: public; Owner: tam
--

ALTER TABLE public.catalog_component ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_component_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: tam
--

CREATE TABLE public.project (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    deleted_by uuid,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    owner_user_id uuid NOT NULL
);


ALTER TABLE public.project OWNER TO tam;

--
-- Name: project_assumption; Type: TABLE; Schema: public; Owner: tam
--

CREATE TABLE public.project_assumption (
    project_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by uuid,
    deleted boolean,
    deleted_at timestamp(6) with time zone,
    deleted_by uuid,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    api_calls_per_request real NOT NULL,
    auth_ratio real NOT NULL,
    cache_ratio_per_request real NOT NULL,
    concurrent_users integer NOT NULL,
    db_ratio_per_request real NOT NULL,
    headroom real NOT NULL,
    kafka_ratio_per_request real NOT NULL,
    log_bytes_per_request integer NOT NULL,
    requests_per_user_per_second real NOT NULL,
    search_ratio_per_request real NOT NULL
);


ALTER TABLE public.project_assumption OWNER TO tam;

--
-- Name: project_catalog_component_seletions; Type: TABLE; Schema: public; Owner: tam
--

CREATE TABLE public.project_catalog_component_seletions (
    project_id bigint NOT NULL,
    catalog_component_id bigint NOT NULL
);


ALTER TABLE public.project_catalog_component_seletions OWNER TO tam;

--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: tam
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: tam
--

CREATE TABLE public.users (
    active boolean,
    deleted boolean,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    created_by uuid,
    deleted_by uuid,
    id uuid NOT NULL,
    updated_by uuid,
    username character varying(100) NOT NULL,
    email character varying(120),
    full_name character varying(200),
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO tam;

--
-- Name: catalog_component catalog_component_pkey; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.catalog_component
    ADD CONSTRAINT catalog_component_pkey PRIMARY KEY (id);


--
-- Name: project_assumption project_assumption_pkey; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project_assumption
    ADD CONSTRAINT project_assumption_pkey PRIMARY KEY (project_id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: project_catalog_component_seletions uki5iu7pf2gnsdlsp2ifejih066; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project_catalog_component_seletions
    ADD CONSTRAINT uki5iu7pf2gnsdlsp2ifejih066 UNIQUE (project_id, catalog_component_id);


--
-- Name: catalog_component ukphnfx07v87mfmiq6rsvci1oco; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.catalog_component
    ADD CONSTRAINT ukphnfx07v87mfmiq6rsvci1oco UNIQUE (component_key);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: project fkbae3bnwveolm0lpl6njt46i6q; Type: FK CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fkbae3bnwveolm0lpl6njt46i6q FOREIGN KEY (owner_user_id) REFERENCES public.users(id);


--
-- Name: project_assumption fkby4m8i3mbe5drocgpsmitglwk; Type: FK CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project_assumption
    ADD CONSTRAINT fkby4m8i3mbe5drocgpsmitglwk FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project_catalog_component_seletions fkcw6fa04n3bq1a4h9c3miugvbj; Type: FK CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project_catalog_component_seletions
    ADD CONSTRAINT fkcw6fa04n3bq1a4h9c3miugvbj FOREIGN KEY (catalog_component_id) REFERENCES public.catalog_component(id);


--
-- Name: project_catalog_component_seletions fkexvv3grpoma4jmbx36e0mcwtd; Type: FK CONSTRAINT; Schema: public; Owner: tam
--

ALTER TABLE ONLY public.project_catalog_component_seletions
    ADD CONSTRAINT fkexvv3grpoma4jmbx36e0mcwtd FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- PostgreSQL database dump complete
--

-- \unrestrict v3OO9YPjRzMqjjRJiquerHReaQzYhRoadvS0EsuNI8XrWNXeyTp53tqtaY0xY0r

