INSERT INTO catalog_component (component_key,
                               name,
                               feature_name,
                               machine_spec,
                               per_machine_capacity,
                               capacity_unit,
                               capacity_unit_description,
                               ha_minimum,
                               reference_url,
                               is_active,
                               deleted)
VALUES ('WEB_NGINX',
        'Web / Nginx',
        'Tiếp nhận request web (RPS)',
        '2 vCPU, 4 GB RAM',
        5000,
        'RPS',
        'Tổng số request/giây của hệ thống, được tính từ số user đồng thời và tần suất thao tác',
        2,
        'https://nginx.org/en/docs/',
        true,
        false),
       ('API_APP',
        'API / App',
        'Xử lý API backend (API calls/sec)',
        '16 vCPU, 32 GB RAM',
        1000,
        'API calls/sec',
        'Tổng số lần gọi API backend, tính theo số request và số API call trung bình mỗi request',
        4,
        'https://tomcat.apache.org/tomcat-9.0-doc/config/http.html',
        true,
        false),
       ('ORACLE_DB',
        'Oracle DB',
        'Giao dịch cơ sở dữ liệu (DB TPS)',
        '16 CPU, 32 GB RAM',
        1000,
        'TPS',
        'Số giao dịch truy cập cơ sở dữ liệu mỗi giây, tính theo tỷ lệ API có truy vấn DB',
        2,
        'https://docs.oracle.com/cd/E65398_03/otn/pdf/hardware/html_edmhs/output/chapter_2.htm',
        true,
        false),
       ('ELASTICSEARCH',
        'Elasticsearch',
        'Tìm kiếm dữ liệu (Search QPS)',
        '16 vCPU, 64 GB RAM',
        1000,
        'QPS',
        'Số truy vấn tìm kiếm mỗi giây, tính theo tỷ lệ request có sử dụng chức năng tìm kiếm',
        3,
        'https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html',
        true,
        false),
       ('REDIS_CACHE',
        'Redis Cache',
        'Cache dữ liệu nóng (Cache OPS)',
        '4 vCPU, 32 GB RAM',
        1000,
        'OPS',
        'Số thao tác cache mỗi giây, phản ánh lượng truy cập Redis hoặc hệ thống cache',
        3,
        'https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/benchmarks/',
        true,
        false),
       ('KAFKA',
        'Kafka',
        'Streaming / hàng đợi sự kiện',
        '8 core, 16 GB RAM',
        1000,
        'msg/s',
        'Số message/event phát sinh mỗi giây, phục vụ xử lý bất đồng bộ và ghi log',
        3,
        'https://knowledgecenter.gcora.genpact.com/help/kafka-cluster-minimum-requirements',
        true,
        false),
       ('PROMETHEUS',
        'Prometheus',
        'Monitor hệ thống',
        '4 core, 16gb RAM',
        30,
        'series/giây',
        'Số time series được thu thập và ghi mỗi giây bởi hệ thống monitor',
        2,
        'https://www.alibabacloud.com/help/en/arms/prometheus-monitoring/relationship-between-the-number-of-metrics-collected-by-the-prometheus-agent-and-the-cpu-and-memory-resources',
        true,
        false),
       ('IBM_INSTANA',
        'IBM instana',
        'Monitor ứng dụng',
        '16 core, 64gb RAM',
        10000,
        'span/giây',
        'Lượng metric của ứng dụng tối đa. Tính trên 8 metrics 1 request',
        3,
        'https://www.ibm.com/docs/en/instana-observability/1.0.315?topic=cluster-system-requirements',
        true,
        false),
       ('ETL_STACK',
        'Airflow, dbt, spark',
        'ETL data',
        '16 core, 64gb RAM',
        20,
        'GB/ngày',
        'Tính toán số dung lượng cần ETL theo ngày. Qui đổi ra GB',
        3,
        'https://airflow.apache.org/docs/apache-airflow/stable/installation/prerequisites.html , https://spark.apache.org/docs/latest/hardware-provisioning.html',
        true,
        false),
       ('LOKI',
        'LOKI',
        'Logging tập trung',
        '8 core, 16gb RAM',
        3200,
        'MB/giây',
        'Dung lượng log mà phần mềm sinh ra đơn vị tính theo MB',
        3,
        'https://grafana.com/docs/loki/latest/setup/size/',
        true,
        false),
       ('APISIX',
        'APISIX',
        'API gateway',
        '8 core, 16GB RAM',
        50000,
        'RPS',
        'Tổng số lần gọi API backend, tính theo số request và số API call trung bình mỗi request',
        3,
        'https://apisix.apache.org/docs/apisix/benchmark/',
        true,
        false),
       ('K8S_MASTER',
        'K8s MASTER',
        'Quản lý cụm kubernetes',
        '4 core, 16gb RAM',
        6,
        'worker/node',
        'Số lượng worker node mà mỗi K8s master quản lý được',
        3,
        'https://docs.oracle.com/en/operating-systems/olcne/1.1/relnotes/hosts.html',
        true,
        false),
       ('AUTH_IAM',
        'Auth / IAM',
        'Xác thực người dùng (Auth call/s)',
        '8 vCPU, 16 GB RAM',
        1000,
        'auth call/s',
        'Số yêu cầu xác thực mỗi giây, tính theo tỷ lệ API có kiểm tra xác thực',
        2,
        'https://tomcat.apache.org/tomcat-9.0-doc/config/http.html',
        true,
        false);
